### ISSUE TITLE
Ambiguities in Task3

### ISSUE THREAD

**Issue by Schubisu** [Schubisu/machinelearning_in_r#2]
Hey everyone,
I finished sub-task 3, but I'm not sure if I understood the questions correctly every time.

1. In 3.4 I am manually bootstrapping `Sales` means, but it's not specified how many entries should be drawn from the data set. I randomly picked 10000 values, not sure if that makes sense?

2. In 3.5 the instructions are 

> Repeat the above analysis using `boot()`

I'm not sure if I understood `above analysis` correctly; what I did was to re-run the linear model using the predictors from 3.3 and bootstrapping the MSE and MSE CI as calculated in 3.2. It made the most sense to me, any ideas if I misunderstood the task?

**Comment by LuKunze** [comment]
Hey! 

concerning 1.) Yes, it does make sense!!
I looked up the bootstrap chapter in the book and they also use 1.000 bootstrap samples in their examples. Also the Carseats dataset has 400 observations it makes sense to use quite more values for understanding the potentail distribution!

concerning 2.) 
I think he just wants us to use the boot() demand from the package instead of the sample(replace=F). So he just wants us to understand the syntax of this demand and just repeat and compare I think..

One small thing that I additionally found: for task 3.2.d) there is still the question "indicating what?"
 We should just explain that the MSE only differs slightly because the different set.seeds() choose different data randomly. Because of the different datapoints it is not exact the same, but differs only slightly.
